#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./client && yarn types && yarn lint --fix && yarn check-types && git add src/types/generated/

CMS_ENV_FILE="./cms/.env"

if [[ -f "$CMS_ENV_FILE" ]] ; then
    echo "Exporting CMS config"
    cd .. && cd ./cms && yarn config-sync export -y && git add config/sync/*
fi
